package com.duanying.dao;

import com.duanying.model.BookSelf;

public interface BookSelfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookself
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookself
     *
     * @mbg.generated
     */
    int insert(BookSelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookself
     *
     * @mbg.generated
     */
    int insertSelective(BookSelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookself
     *
     * @mbg.generated
     */
    BookSelf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookself
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookSelf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookself
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookSelf record);
}