package com.duanying.dao;

import com.duanying.model.BookType;
import com.duanying.model.BookTypeKey;

public interface BookTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BookTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated
     */
    int insert(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated
     */
    int insertSelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated
     */
    BookType selectByPrimaryKey(BookTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookType record);
}