package com.duanying.dao;

import java.util.List;

import com.duanying.impl.dto.BookDto;
import com.duanying.model.Book;

public interface BookMapper {	
	
	/**
	 * 最新更新
	 * @return
	 */
	List<BookDto> updateLeast();
	
	/**
	 * 精彩完本
	 * @return
	 */
	List<BookDto> bookOver();
	/**
	 * 人气连载
	 * @return
	 */
	List<BookDto> hotWriteing();
	/**
	 * 言情推荐
	 * @return
	 */
	List<BookDto> remantic();
	/**
	 * 编辑推荐
	 * @return
	 */
	List<BookDto> editerRecom();
	/**
	 * 月榜
	 * @return
	 */
	List<BookDto> monthTopTen();
	
	/**
	 * 周榜
	 * @return
	 */
	List<BookDto> weekTopTen();
	
	/**
	 * 热门分类
	 * @return
	 */
	List<BookDto> selectByTypes();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbg.generated
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbg.generated
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbg.generated
     */
    BookDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Book record);
}