package com.duanying.dao;

import com.duanying.model.Discuss;

public interface DiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated
     */
    int insert(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated
     */
    int insertSelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated
     */
    Discuss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discuss
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Discuss record);
}