package com.duanying.dao;

import com.duanying.model.MonthTicket;

public interface MonthTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_month_ticket
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_month_ticket
     *
     * @mbg.generated
     */
    int insert(MonthTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_month_ticket
     *
     * @mbg.generated
     */
    int insertSelective(MonthTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_month_ticket
     *
     * @mbg.generated
     */
    MonthTicket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_month_ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MonthTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_month_ticket
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonthTicket record);
}