package com.duanying.model;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_author.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_author.author_name
     *
     * @mbg.generated
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_author.author_img
     *
     * @mbg.generated
     */
    private String authorImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_author.descript
     *
     * @mbg.generated
     */
    private String descript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_author.id
     *
     * @return the value of t_author.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_author.id
     *
     * @param id the value for t_author.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_author.author_name
     *
     * @return the value of t_author.author_name
     *
     * @mbg.generated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_author.author_name
     *
     * @param authorName the value for t_author.author_name
     *
     * @mbg.generated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_author.author_img
     *
     * @return the value of t_author.author_img
     *
     * @mbg.generated
     */
    public String getAuthorImg() {
        return authorImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_author.author_img
     *
     * @param authorImg the value for t_author.author_img
     *
     * @mbg.generated
     */
    public void setAuthorImg(String authorImg) {
        this.authorImg = authorImg == null ? null : authorImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_author.descript
     *
     * @return the value of t_author.descript
     *
     * @mbg.generated
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_author.descript
     *
     * @param descript the value for t_author.descript
     *
     * @mbg.generated
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }
}