package com.duanying.model;

import java.io.Serializable;

public class Book implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.descript
     *
     * @mbg.generated
     */
    private String descript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.author_id
     *
     * @mbg.generated
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.txt_count
     *
     * @mbg.generated
     */
    private Integer txtCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.week_ticket
     *
     * @mbg.generated
     */
    private Integer weekTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.month_ticket
     *
     * @mbg.generated
     */
    private Integer monthTicket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.lastest_chapter
     *
     * @mbg.generated
     */
    private Integer lastestChapter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_level
     *
     * @mbg.generated
     */
    private Double bookLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_img
     *
     * @mbg.generated
     */
    private String bookImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_status
     *
     * @mbg.generated
     */
    private String bookStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_label
     *
     * @mbg.generated
     */
    private String bookLabel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.id
     *
     * @return the value of t_book.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.id
     *
     * @param id the value for t_book.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.type_id
     *
     * @return the value of t_book.type_id
     *
     * @mbg.generated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.type_id
     *
     * @param typeId the value for t_book.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_name
     *
     * @return the value of t_book.book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_name
     *
     * @param bookName the value for t_book.book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.descript
     *
     * @return the value of t_book.descript
     *
     * @mbg.generated
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.descript
     *
     * @param descript the value for t_book.descript
     *
     * @mbg.generated
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.author_id
     *
     * @return the value of t_book.author_id
     *
     * @mbg.generated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.author_id
     *
     * @param authorId the value for t_book.author_id
     *
     * @mbg.generated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.txt_count
     *
     * @return the value of t_book.txt_count
     *
     * @mbg.generated
     */
    public Integer getTxtCount() {
        return txtCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.txt_count
     *
     * @param txtCount the value for t_book.txt_count
     *
     * @mbg.generated
     */
    public void setTxtCount(Integer txtCount) {
        this.txtCount = txtCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.week_ticket
     *
     * @return the value of t_book.week_ticket
     *
     * @mbg.generated
     */
    public Integer getWeekTicket() {
        return weekTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.week_ticket
     *
     * @param weekTicket the value for t_book.week_ticket
     *
     * @mbg.generated
     */
    public void setWeekTicket(Integer weekTicket) {
        this.weekTicket = weekTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.month_ticket
     *
     * @return the value of t_book.month_ticket
     *
     * @mbg.generated
     */
    public Integer getMonthTicket() {
        return monthTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.month_ticket
     *
     * @param monthTicket the value for t_book.month_ticket
     *
     * @mbg.generated
     */
    public void setMonthTicket(Integer monthTicket) {
        this.monthTicket = monthTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.lastest_chapter
     *
     * @return the value of t_book.lastest_chapter
     *
     * @mbg.generated
     */
    public Integer getLastestChapter() {
        return lastestChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.lastest_chapter
     *
     * @param lastestChapter the value for t_book.lastest_chapter
     *
     * @mbg.generated
     */
    public void setLastestChapter(Integer lastestChapter) {
        this.lastestChapter = lastestChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_level
     *
     * @return the value of t_book.book_level
     *
     * @mbg.generated
     */
    public Double getBookLevel() {
        return bookLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_level
     *
     * @param bookLevel the value for t_book.book_level
     *
     * @mbg.generated
     */
    public void setBookLevel(Double bookLevel) {
        this.bookLevel = bookLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_img
     *
     * @return the value of t_book.book_img
     *
     * @mbg.generated
     */
    public String getBookImg() {
        return bookImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_img
     *
     * @param bookImg the value for t_book.book_img
     *
     * @mbg.generated
     */
    public void setBookImg(String bookImg) {
        this.bookImg = bookImg == null ? null : bookImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_status
     *
     * @return the value of t_book.book_status
     *
     * @mbg.generated
     */
    public String getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_status
     *
     * @param bookStatus the value for t_book.book_status
     *
     * @mbg.generated
     */
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus == null ? null : bookStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_label
     *
     * @return the value of t_book.book_label
     *
     * @mbg.generated
     */
    public String getBookLabel() {
        return bookLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_label
     *
     * @param bookLabel the value for t_book.book_label
     *
     * @mbg.generated
     */
    public void setBookLabel(String bookLabel) {
        this.bookLabel = bookLabel == null ? null : bookLabel.trim();
    }
}