package com.duanying.model;

import java.util.Date;

public class BookSelf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookself.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookself.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookself.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookself.read_book_id
     *
     * @mbg.generated
     */
    private Integer readBookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookself.collection_time
     *
     * @mbg.generated
     */
    private Date collectionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookself.last_chapter
     *
     * @mbg.generated
     */
    private Integer lastChapter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookself.id
     *
     * @return the value of t_bookself.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookself.id
     *
     * @param id the value for t_bookself.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookself.user_id
     *
     * @return the value of t_bookself.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookself.user_id
     *
     * @param userId the value for t_bookself.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookself.book_id
     *
     * @return the value of t_bookself.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookself.book_id
     *
     * @param bookId the value for t_bookself.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookself.read_book_id
     *
     * @return the value of t_bookself.read_book_id
     *
     * @mbg.generated
     */
    public Integer getReadBookId() {
        return readBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookself.read_book_id
     *
     * @param readBookId the value for t_bookself.read_book_id
     *
     * @mbg.generated
     */
    public void setReadBookId(Integer readBookId) {
        this.readBookId = readBookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookself.collection_time
     *
     * @return the value of t_bookself.collection_time
     *
     * @mbg.generated
     */
    public Date getCollectionTime() {
        return collectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookself.collection_time
     *
     * @param collectionTime the value for t_bookself.collection_time
     *
     * @mbg.generated
     */
    public void setCollectionTime(Date collectionTime) {
        this.collectionTime = collectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookself.last_chapter
     *
     * @return the value of t_bookself.last_chapter
     *
     * @mbg.generated
     */
    public Integer getLastChapter() {
        return lastChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookself.last_chapter
     *
     * @param lastChapter the value for t_bookself.last_chapter
     *
     * @mbg.generated
     */
    public void setLastChapter(Integer lastChapter) {
        this.lastChapter = lastChapter;
    }
}