package com.duanying.model;

public class BookType extends BookTypeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book_type.type_parent
     *
     * @mbg.generated
     */
    private Integer typeParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book_type.type_parent
     *
     * @return the value of t_book_type.type_parent
     *
     * @mbg.generated
     */
    public Integer getTypeParent() {
        return typeParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book_type.type_parent
     *
     * @param typeParent the value for t_book_type.type_parent
     *
     * @mbg.generated
     */
    public void setTypeParent(Integer typeParent) {
        this.typeParent = typeParent;
    }
}