package com.duanying.model;

public class Discuss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discuss.discuss_to_user_id
     *
     * @mbg.generated
     */
    private Integer discussToUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.id
     *
     * @return the value of t_discuss.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.id
     *
     * @param id the value for t_discuss.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.book_id
     *
     * @return the value of t_discuss.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.book_id
     *
     * @param bookId the value for t_discuss.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.user_id
     *
     * @return the value of t_discuss.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.user_id
     *
     * @param userId the value for t_discuss.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.content
     *
     * @return the value of t_discuss.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.content
     *
     * @param content the value for t_discuss.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discuss.discuss_to_user_id
     *
     * @return the value of t_discuss.discuss_to_user_id
     *
     * @mbg.generated
     */
    public Integer getDiscussToUserId() {
        return discussToUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discuss.discuss_to_user_id
     *
     * @param discussToUserId the value for t_discuss.discuss_to_user_id
     *
     * @mbg.generated
     */
    public void setDiscussToUserId(Integer discussToUserId) {
        this.discussToUserId = discussToUserId;
    }
}