package com.duanying.model;

public class Label {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_label.label_name
     *
     * @mbg.generated
     */
    private String labelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.id
     *
     * @return the value of t_label.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.id
     *
     * @param id the value for t_label.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_label.label_name
     *
     * @return the value of t_label.label_name
     *
     * @mbg.generated
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_label.label_name
     *
     * @param labelName the value for t_label.label_name
     *
     * @mbg.generated
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }
}